# Generated by Django 5.1.4 on 2024-12-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
